### ISSUE TITLE
Adding more camera trajectory positions

### ISSUE THREAD

**Issue by SmileLars** [ddiakopoulos/polymer#42]
Is there an easy way to add more camera trajectory position?
It seem to bug out when adding more than 4.
It is probably me doing something wrong, not understanding the code completely.

Ps.
Keep up the amazing work you are doing, you are brilliant! 😍

**Comment by ddiakopoulos** [comment]
Hi @SmileLars sorry it took so long for me to see this - I haven't looked at the issues queue for the repo for a long time (clearly) and didn't get any notifications. Would you like some help with this or have you moved on?
